# https://travis-ci.org/ryanss/holidays.py

language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy

install:
    - python setup.py install
    - pip install flake8
    - pip install coveralls

before_script:
    - flake8 holidays.py tests.py

script:
    - coverage run --omit=*site-packages*,*pypy* tests.py

after_success:
    - coveralls
